version: '3'

services:
    php:
        image: php:8.2-apache
        volumes:
            - .:/var/www/html
        ports:
            - 15000:80
        container_name: php7.2-trial2-type2
    mysql:
        platform: linux/x86_64 #Mac M1
        image: mysql:5.7
        volumes:
            #- /var/lib/mysql
            - ./mysql_data:/var/lib/mysql

        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            #- MYSQL_USER=root
            #- MYSQL_PASSWORD=root
        container_name: mysql5.7-trial2-typ2

